name: macos_tests

on:
    push:
        branches:
            - main  # Change this to your main branch name if different

jobs:

    macos14:
        runs-on: macos-14
        strategy:
            matrix:
                python-version: [ '3.10', '3.11' ]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: pip install -r requirements.txt

            -   name: Run unit tests
                run: python -m unittest discover -s ./tests -t .


    macos13:
        runs-on: macos-13
        strategy:
            matrix:
                python-version: [ '3.10', '3.11' ]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: pip install -r requirements.txt

            -   name: Run unit tests
                run: python -m unittest discover -s ./tests -t .